CXX = C:/cygwin64/bin/g++
CXXFLAGS = -Wall -Wextra -O2
LDFLAGS =
TARGET = test_telemetry_sender

SRC = main.cpp f1_23_packet_builder.cpp
OBJ = $(SRC:.cpp=.o)

all: $(TARGET)

$(TARGET): $(OBJ)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJ) $(LDFLAGS)

clean:
	rm -f $(OBJ) $(TARGET)
